### ISSUE TITLE
Side Menu - Homes - Save homes

### ISSUE THREAD

**Issue by tomasgnr** [JerusMunchkins/loco#42]
**Summary:**
As a user, I would like to save my homes so I can compare them

**Implementation:**
- Add button by the address inputs will save the apartment in the store and or database
- The saved/stored homes will be displayed as components on the Homes tab on top of the filters

**Comment by codaboba** [comment]
- [ ] GET all user's homes /api/users/:userId/homes
- [ ] POST user's home
  - [ ] POST /api/location - must make call to google places API
  - [ ] POST /api/home using result from POST /api/location (and update user_homes tables)?
